[package]
name = "morse-code"
version = "0.1.0"
authors = ["matthew Whited <matt@whited.us>"]
edition = "2018"

[dependencies]

[dev-dependencies]

[[bin]]
name = "morse-code"
path = "morse_code.rs"

[profile.release]
opt-level = 3